package com.project.fpt.sfm.entities;
// Generated Oct 12, 2015 2:10:19 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FinancialType generated by hbm2java
 */
@Entity
@Table(name="financial_type"
    ,catalog="sfm"
)
public class FinancialType  implements java.io.Serializable {


     private Integer financialTypeId;
     private String financialTypeName;
     private int financialRate;
     private String note;
     private Boolean isActive;
     private Date dateCreated;
     private Date dateUpdated;
     private Set<Student> students = new HashSet<Student>(0);

    public FinancialType() {
    }

	
    public FinancialType(String financialTypeName, int financialRate) {
        this.financialTypeName = financialTypeName;
        this.financialRate = financialRate;
    }
    public FinancialType(String financialTypeName, int financialRate, String note, Boolean isActive, Date dateCreated, Date dateUpdated, Set<Student> students) {
       this.financialTypeName = financialTypeName;
       this.financialRate = financialRate;
       this.note = note;
       this.isActive = isActive;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
       this.students = students;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="FinancialTypeID", unique=true, nullable=false)
    public Integer getFinancialTypeId() {
        return this.financialTypeId;
    }
    
    public void setFinancialTypeId(Integer financialTypeId) {
        this.financialTypeId = financialTypeId;
    }

    
    @Column(name="FinancialTypeName", nullable=false, length=45)
    public String getFinancialTypeName() {
        return this.financialTypeName;
    }
    
    public void setFinancialTypeName(String financialTypeName) {
        this.financialTypeName = financialTypeName;
    }

    
    @Column(name="FinancialRate", nullable=false)
    public int getFinancialRate() {
        return this.financialRate;
    }
    
    public void setFinancialRate(int financialRate) {
        this.financialRate = financialRate;
    }

    
    @Column(name="Note", length=65535)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="IsActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Date_Created", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateUpdated", length=19)
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="financialType")
    public Set<Student> getStudents() {
        return this.students;
    }
    
    public void setStudents(Set<Student> students) {
        this.students = students;
    }




}


