package com.project.fpt.sfm.entities;
// Generated Oct 12, 2015 2:10:19 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * InvestmentStudent generated by hbm2java
 */
@Entity
@Table(name="investment_student"
    ,catalog="sfm"
)
public class InvestmentStudent  implements java.io.Serializable {


     private int studentId;
     private Student student;
     private int investmentRate;
     private String note;
     private Boolean isActive;
     private Date dateCreated;
     private Date dateUpdated;
     private Set<InvestmentReport> investmentReports = new HashSet<InvestmentReport>(0);

    public InvestmentStudent() {
    }

	
    public InvestmentStudent(Student student, int investmentRate) {
        this.student = student;
        this.investmentRate = investmentRate;
    }
    public InvestmentStudent(Student student, int investmentRate, String note, Boolean isActive, Date dateCreated, Date dateUpdated, Set<InvestmentReport> investmentReports) {
       this.student = student;
       this.investmentRate = investmentRate;
       this.note = note;
       this.isActive = isActive;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
       this.investmentReports = investmentReports;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="student"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="StudentID", unique=true, nullable=false)
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

    
    @Column(name="InvestmentRate", nullable=false)
    public int getInvestmentRate() {
        return this.investmentRate;
    }
    
    public void setInvestmentRate(int investmentRate) {
        this.investmentRate = investmentRate;
    }

    
    @Column(name="Note", length=65535)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="IsActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Date_Created", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateUpdated", length=19)
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="investmentStudent")
    public Set<InvestmentReport> getInvestmentReports() {
        return this.investmentReports;
    }
    
    public void setInvestmentReports(Set<InvestmentReport> investmentReports) {
        this.investmentReports = investmentReports;
    }




}


