package com.project.fpt.sfm.entities;
// Generated Oct 12, 2015 2:10:19 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InvestmentReport generated by hbm2java
 */
@Entity
@Table(name="investment_report"
    ,catalog="sfm"
)
public class InvestmentReport  implements java.io.Serializable {


     private Integer reportId;
     private InvestmentStudent investmentStudent;
     private String totalMoney;
     private String paidMoney;
     private boolean payStatus;
     private String bank;
     private Date dateTransfer;
     private String note;
     private Boolean isActive;
     private Date dateCreated;
     private Date dateUpdated;

    public InvestmentReport() {
    }

	
    public InvestmentReport(InvestmentStudent investmentStudent, String totalMoney, String paidMoney, boolean payStatus) {
        this.investmentStudent = investmentStudent;
        this.totalMoney = totalMoney;
        this.paidMoney = paidMoney;
        this.payStatus = payStatus;
    }
    public InvestmentReport(InvestmentStudent investmentStudent, String totalMoney, String paidMoney, boolean payStatus, String bank, Date dateTransfer, String note, Boolean isActive, Date dateCreated, Date dateUpdated) {
       this.investmentStudent = investmentStudent;
       this.totalMoney = totalMoney;
       this.paidMoney = paidMoney;
       this.payStatus = payStatus;
       this.bank = bank;
       this.dateTransfer = dateTransfer;
       this.note = note;
       this.isActive = isActive;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ReportID", unique=true, nullable=false)
    public Integer getReportId() {
        return this.reportId;
    }
    
    public void setReportId(Integer reportId) {
        this.reportId = reportId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="StudentID", nullable=false)
    public InvestmentStudent getInvestmentStudent() {
        return this.investmentStudent;
    }
    
    public void setInvestmentStudent(InvestmentStudent investmentStudent) {
        this.investmentStudent = investmentStudent;
    }

    
    @Column(name="TotalMoney", nullable=false, length=16777215)
    public String getTotalMoney() {
        return this.totalMoney;
    }
    
    public void setTotalMoney(String totalMoney) {
        this.totalMoney = totalMoney;
    }

    
    @Column(name="PaidMoney", nullable=false, length=16777215)
    public String getPaidMoney() {
        return this.paidMoney;
    }
    
    public void setPaidMoney(String paidMoney) {
        this.paidMoney = paidMoney;
    }

    
    @Column(name="PayStatus", nullable=false)
    public boolean isPayStatus() {
        return this.payStatus;
    }
    
    public void setPayStatus(boolean payStatus) {
        this.payStatus = payStatus;
    }

    
    @Column(name="Bank", length=45)
    public String getBank() {
        return this.bank;
    }
    
    public void setBank(String bank) {
        this.bank = bank;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateTransfer", length=19)
    public Date getDateTransfer() {
        return this.dateTransfer;
    }
    
    public void setDateTransfer(Date dateTransfer) {
        this.dateTransfer = dateTransfer;
    }

    
    @Column(name="Note", length=65535)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="IsActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Date_Created", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateUpdated", length=19)
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }




}


