package com.project.fpt.sfm.entities;
// Generated Oct 12, 2015 2:10:19 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MandatorySubject generated by hbm2java
 */
@Entity
@Table(name="mandatory_subject"
    ,catalog="sfm"
)
public class MandatorySubject  implements java.io.Serializable {


     private Integer mandatorySubId;
     private Subject subjectByRequireSubjectId;
     private Subject subjectBySubjectId;
     private String note;
     private Boolean isActive;
     private Date dateCreated;
     private Date dateUpdated;

    public MandatorySubject() {
    }

	
    public MandatorySubject(Subject subjectByRequireSubjectId, Subject subjectBySubjectId) {
        this.subjectByRequireSubjectId = subjectByRequireSubjectId;
        this.subjectBySubjectId = subjectBySubjectId;
    }
    public MandatorySubject(Subject subjectByRequireSubjectId, Subject subjectBySubjectId, String note, Boolean isActive, Date dateCreated, Date dateUpdated) {
       this.subjectByRequireSubjectId = subjectByRequireSubjectId;
       this.subjectBySubjectId = subjectBySubjectId;
       this.note = note;
       this.isActive = isActive;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="MandatorySubID", unique=true, nullable=false)
    public Integer getMandatorySubId() {
        return this.mandatorySubId;
    }
    
    public void setMandatorySubId(Integer mandatorySubId) {
        this.mandatorySubId = mandatorySubId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RequireSubjectID", nullable=false)
    public Subject getSubjectByRequireSubjectId() {
        return this.subjectByRequireSubjectId;
    }
    
    public void setSubjectByRequireSubjectId(Subject subjectByRequireSubjectId) {
        this.subjectByRequireSubjectId = subjectByRequireSubjectId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SubjectId", nullable=false)
    public Subject getSubjectBySubjectId() {
        return this.subjectBySubjectId;
    }
    
    public void setSubjectBySubjectId(Subject subjectBySubjectId) {
        this.subjectBySubjectId = subjectBySubjectId;
    }

    
    @Column(name="Note", length=65535)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="IsActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Date_Created", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateUpdated", length=19)
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }




}


