package com.project.fpt.sfm.entities;
// Generated Oct 12, 2015 2:10:19 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MoneyRate generated by hbm2java
 */
@Entity
@Table(name="money_rate"
    ,catalog="sfm"
)
public class MoneyRate  implements java.io.Serializable {


     private Integer rateId;
     private float rate;
     private Boolean isActive;
     private Date dateCreated;
     private Date dateUpdated;

    public MoneyRate() {
    }

	
    public MoneyRate(float rate) {
        this.rate = rate;
    }
    public MoneyRate(float rate, Boolean isActive, Date dateCreated, Date dateUpdated) {
       this.rate = rate;
       this.isActive = isActive;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="RateID", unique=true, nullable=false)
    public Integer getRateId() {
        return this.rateId;
    }
    
    public void setRateId(Integer rateId) {
        this.rateId = rateId;
    }

    
    @Column(name="Rate", nullable=false, precision=12, scale=0)
    public float getRate() {
        return this.rate;
    }
    
    public void setRate(float rate) {
        this.rate = rate;
    }

    
    @Column(name="IsActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Date_Created", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateUpdated", length=19)
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }




}


