package com.project.fpt.sfm.entities;
// Generated Oct 15, 2015 7:12:40 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SubtractTuition generated by hbm2java
 */
@Entity
@Table(name="subtract_tuition"
    ,catalog="sfm"
)
public class SubtractTuition  implements java.io.Serializable {


     private Integer subtractTuitionId;
     private TuitionPayment tuitionPayment;
     private String subtractTuitionName;
     private int subtractTuition;
     private String note;
     private Boolean isActive;
     private Date dateCreated;
     private Date dateUpdated;

    public SubtractTuition() {
    }

	
    public SubtractTuition(TuitionPayment tuitionPayment, String subtractTuitionName, int subtractTuition) {
        this.tuitionPayment = tuitionPayment;
        this.subtractTuitionName = subtractTuitionName;
        this.subtractTuition = subtractTuition;
    }
    public SubtractTuition(TuitionPayment tuitionPayment, String subtractTuitionName, int subtractTuition, String note, Boolean isActive, Date dateCreated, Date dateUpdated) {
       this.tuitionPayment = tuitionPayment;
       this.subtractTuitionName = subtractTuitionName;
       this.subtractTuition = subtractTuition;
       this.note = note;
       this.isActive = isActive;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SubtractTuitionID", unique=true, nullable=false)
    public Integer getSubtractTuitionId() {
        return this.subtractTuitionId;
    }
    
    public void setSubtractTuitionId(Integer subtractTuitionId) {
        this.subtractTuitionId = subtractTuitionId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TuitionPaymentID", nullable=false)
    public TuitionPayment getTuitionPayment() {
        return this.tuitionPayment;
    }
    
    public void setTuitionPayment(TuitionPayment tuitionPayment) {
        this.tuitionPayment = tuitionPayment;
    }

    
    @Column(name="SubtractTuitionName", nullable=false, length=45)
    public String getSubtractTuitionName() {
        return this.subtractTuitionName;
    }
    
    public void setSubtractTuitionName(String subtractTuitionName) {
        this.subtractTuitionName = subtractTuitionName;
    }

    
    @Column(name="SubtractTuition", nullable=false)
    public int getSubtractTuition() {
        return this.subtractTuition;
    }
    
    public void setSubtractTuition(int subtractTuition) {
        this.subtractTuition = subtractTuition;
    }

    
    @Column(name="Note", length=65535)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="IsActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Date_Created", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateUpdated", length=19)
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }




}


