package com.project.fpt.sfm.entities;
// Generated Oct 12, 2015 2:10:19 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Term generated by hbm2java
 */
@Entity
@Table(name="term"
    ,catalog="sfm"
)
public class Term  implements java.io.Serializable {


     private Integer termId;
     private String termName;
     private Date startDate;
     private Date endDate;
     private String note;
    private Boolean isActive;
     private Date dateCreated;
     private Date dateUpdated;
     private boolean isCurrent;
     private Set<Semester> semesters = new HashSet<Semester>(0);

    public Term() {
        this.dateCreated = new Date();
        this.dateUpdated = new Date();
        this.isActive = true;
        this.note = "-";
    }

	
    public Term(String termName, boolean isActive, boolean isCurrent) {
        this.termName = termName;
        this.isActive = isActive;
        this.isCurrent = isCurrent;
    }
    public Term(String termName, Date startDate, Date endDate, String note, boolean isActive, Date dateCreated, Date dateUpdated, boolean isCurrent, Set<Semester> semesters) {
       this.termName = termName;
       this.startDate = startDate;
       this.endDate = endDate;
       this.note = note;
       this.isActive = isActive;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
       this.isCurrent = isCurrent;
       this.semesters = semesters;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TermID", unique=true, nullable=false)
    public Integer getTermId() {
        return this.termId;
    }
    
    public void setTermId(Integer termId) {
        this.termId = termId;
    }

    
    @Column(name="TermName", nullable=false, length=45)
    public String getTermName() {
        return this.termName;
    }
    
    public void setTermName(String termName) {
        this.termName = termName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="StartDate", length=19)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EndDate", length=19)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="Note", length=65535)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }


    @Column(name="IsActive")
    public Boolean getIsActive() {
        return this.isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Date_Created", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateUpdated", length=19)
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }

    
    @Column(name="IsCurrent", nullable=false)
    public boolean isIsCurrent() {
        return this.isCurrent;
    }
    
    public void setIsCurrent(boolean isCurrent) {
        this.isCurrent = isCurrent;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="term")
    public Set<Semester> getSemesters() {
        return this.semesters;
    }
    
    public void setSemesters(Set<Semester> semesters) {
        this.semesters = semesters;
    }




}


