package com.project.fpt.sfm.entities;
// Generated Oct 13, 2015 7:12:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TuitionPlan generated by hbm2java
 */
@Entity
@Table(name="tuition_plan"
    ,catalog="sfm"
)
public class TuitionPlan  implements java.io.Serializable {
     private Integer tuitionPlanId;
     private Student student;
     private Term term;
     private String tuitionName;
     private int tuition;
     private String tuitionType;

    public TuitionPlan() {
    }

	
    public TuitionPlan(Student student, Term term, String tuitionName, int tuition) {
        this.student = student;
        this.term = term;
        this.tuitionName = tuitionName;
        this.tuition = tuition;
    }
    public TuitionPlan(Student student, Term term, String tuitionName, int tuition, String tuitionType) {
       this.student = student;
       this.term = term;
       this.tuitionName = tuitionName;
       this.tuition = tuition;
       this.tuitionType = tuitionType;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TuitionPlanID", unique=true, nullable=false)
    public Integer getTuitionPlanId() {
        return this.tuitionPlanId;
    }
    
    public void setTuitionPlanId(Integer tuitionPlanId) {
        this.tuitionPlanId = tuitionPlanId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="StudentID", nullable=false)
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TermID", nullable=false)
    public Term getTerm() {
        return this.term;
    }
    
    public void setTerm(Term term) {
        this.term = term;
    }

    
    @Column(name="TuitionName", nullable=false, length=64)
    public String getTuitionName() {
        return this.tuitionName;
    }
    
    public void setTuitionName(String tuitionName) {
        this.tuitionName = tuitionName;
    }

    
    @Column(name="Tuition", nullable=false)
    public int getTuition() {
        return this.tuition;
    }
    
    public void setTuition(int tuition) {
        this.tuition = tuition;
    }

    
    @Column(name="TuitionType", length=125)
    public String getTuitionType() {
        return this.tuitionType;
    }
    
    public void setTuitionType(String tuitionType) {
        this.tuitionType = tuitionType;
    }




}


